<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="Uploads\PDFs\BankingSystem_20250521120803.pdf" />
    <Content Include="Uploads\PDFs\Capstone_Project_PPT_Poonam_20250502153544_20250521124228.pdf" />
    <Content Include="Uploads\PDFs\Capstone_Project_PPT_Poonam_20250502153544_20250522130301.pdf" />
    <Content Include="Uploads\PDFs\EventBookingSystem_20250527164949.pdf" />
    <Content Include="Uploads\PDFs\NS_Data_Management_Module_SRS_1.2_20250502144727_20250502192418_20250522130255.pdf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="EPPlus" Version="8.0.3" />
    <PackageReference Include="Microsoft.AspNetCore.Identity" Version="2.3.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.4" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="9.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Core\DataMgmtModule.Application\DataMgmtModule.Application.csproj" />
    <ProjectReference Include="..\..\Infrastructure\DataMgmtModule.Identity\DataMgmtModule.Identity.csproj" />
    <ProjectReference Include="..\..\Infrastructure\DataMgmtModule.Persistence\DataMgmtModule.Persistence.csproj" />
  </ItemGroup>

</Project>
